// src/app/layout.tsx

// Import cn utility and ThemeProvider from shadcn/ui
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        {/* Wrap children with ThemeProvider and set defaultTheme to "dark" */}
        <ThemeProvider
          attribute="class" // This tells next-themes to apply 'dark' class to html tag
          defaultTheme="dark" // <--- Set default theme to dark
          enableSystem // Allows users to switch to system preference
          disableTransitionOnChange // Prevents flash of unstyled content on theme change
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

